=== de2164/dpcanada/prod/c/feeds/projects.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="projects">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="project" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="project">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nameofwork"/>
				<xsd:element ref="authorsname"/>
				<xsd:element ref="language"/>
				<xsd:element ref="posteddate"/>
				<xsd:element ref="genre"/>
				<xsd:element ref="links"/>
			</xsd:sequence>
			<xsd:attribute name="id" use="required" type="xsd:ID"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="nameofwork" type="xsd:string"/>
	<xsd:element name="authorsname" type="xsd:string"/>
	<xsd:element name="language" type="xsd:string"/>
	<xsd:element name="posteddate" type="xsd:string"/>
	<xsd:element name="genre" type="xsd:string"/>
	<xsd:element name="links">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="text"/>
				<xsd:element ref="zip"/>
				<xsd:element ref="html"/>
				<xsd:element ref="library"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="text" type="xsd:string"/>
	<xsd:element name="zip" type="xsd:string"/>
	<xsd:element name="html" type="xsd:string"/>
	<xsd:element name="library" type="xsd:string"/>
</xsd:schema>

=== de2164/dpcanada/trunk/d/xmlfeeds/proofing.xml
<?xml version="1.0" encoding="utf-8" ?>
				<!-- Last Updated: Fri, 01 Feb 2013 17:22:48 -0500 -->
				<projects xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:noNamespaceSchemaLocation="projects.xsd">
				<project id="projectID501aff0a23c47">
				<nameofwork>The Beckoning Hand: The Search Party&#039;s Find</nameofwork>
				<authorsname>Allen, Grant</authorsname>
				<language>English</language>
				<posteddate>Thu, 31 Jan 2013 21:25:03 -0500</posteddate>
				<genre>Short Story</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID501aff0a23c47</library>
				</links>
				</project>
				<project id="projectID4fbecbff7bf0c">
				<nameofwork>Fun-jottings; or, Laughs I have taken a pen to (1854)</nameofwork>
				<authorsname>Willis, N.P. (Nathaniel Parker) 1806-1867</authorsname>
				<language>English</language>
				<posteddate>Wed, 30 Jan 2013 06:45:53 -0500</posteddate>
				<genre>Humor</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4fbecbff7bf0c</library>
				</links>
				</project>
				<project id="projectID50f4c0b93dfc7">
				<nameofwork>La bibliothèque canadienne, Tome 3, Nº 03 Aout 1826</nameofwork>
				<authorsname>Various</authorsname>
				<language>French</language>
				<posteddate>Wed, 30 Jan 2013 06:44:08 -0500</posteddate>
				<genre>Literature</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID50f4c0b93dfc7</library>
				</links>
				</project>
				<project id="projectID50f2e927a7ad3">
				<nameofwork>The Canadian Horticulturist Volume 08, No. 06</nameofwork>
				<authorsname>The Fruit Growers Association of Ontario</authorsname>
				<language>English</language>
				<posteddate>Wed, 30 Jan 2013 06:43:26 -0500</posteddate>
				<genre>Horticulture</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID50f2e927a7ad3</library>
				</links>
				</project>
				<project id="projectID50fc7858f0b5e">
				<nameofwork>Geschichte der Deutschen Zeichnung und Graphik (1951)</nameofwork>
				<authorsname>Fischer, Otto (1886-1948)</authorsname>
				<language>German</language>
				<posteddate>Sun, 27 Jan 2013 21:12:32 -0500</posteddate>
				<genre>Art</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID50fc7858f0b5e</library>
				</links>
				</project>
				<project id="projectID510201ded601d">
				<nameofwork>Harper of Heaven (1948)</nameofwork>
				<authorsname>Service, Robert William (1874-1958)</authorsname>
				<language>English</language>
				<posteddate>Sat, 26 Jan 2013 23:08:51 -0500</posteddate>
				<genre>Autobiography</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID510201ded601d</library>
				</links>
				</project>
				<project id="projectID510192656c30a">
				<nameofwork>Face Cards (1925)</nameofwork>
				<authorsname>Carolyn Wells (1862-1942)</authorsname>
				<language>English</language>
				<posteddate>Sat, 26 Jan 2013 23:07:59 -0500</posteddate>
				<genre>Poetry</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID510192656c30a</library>
				</links>
				</project>
				<project id="projectID510130c1ac66a">
				<nameofwork>Out of Africa (1937)</nameofwork>
				<authorsname>Karen Blixen (1885-1962)</authorsname>
				<language>English</language>
				<posteddate>Sat, 26 Jan 2013 23:07:33 -0500</posteddate>
				<genre>Non-Fiction</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID510130c1ac66a</library>
				</links>
				</project>
				<project id="projectID5095399baf862">
				<nameofwork>Hester vol. 3 (1883)</nameofwork>
				<authorsname>Oliphant, Margaret (1828-1897)</authorsname>
				<language>English</language>
				<posteddate>Thu, 24 Jan 2013 18:57:11 -0500</posteddate>
				<genre>General Fiction</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID5095399baf862</library>
				</links>
				</project>
				<project id="projectID50fddfb20fd2d">
				<nameofwork>First Furrows (1923)</nameofwork>
				<authorsname>Alfred Campbell Garrioch (1848-1934)</authorsname>
				<language>English</language>
				<posteddate>Wed, 23 Jan 2013 19:02:18 -0500</posteddate>
				<genre>History</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID50fddfb20fd2d</library>
				</links>
				</project>
				
				</projects>

=== de2164/dpcanada/trunk/d/xmlfeeds/postprocessing.xml
<?xml version="1.0" encoding="utf-8" ?>
				<!-- Last Updated: Fri, 01 Feb 2013 19:49:00 -0500 -->
				<projects xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:noNamespaceSchemaLocation="projects.xsd">
				<project id="projectID4f80a56494915">
				<nameofwork>Christmas Holidays, or, a new way of spending them (1863)</nameofwork>
				<authorsname>Strickland, Jane Margaret 1800-1888</authorsname>
				<language>English</language>
				<posteddate>Fri, 01 Feb 2013 07:15:00 -0500</posteddate>
				<genre>Instructional</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4f80a56494915</library>
				</links>
				</project>
				<project id="projectID4f96abd9ddb1a">
				<nameofwork>Manual of the Wood-craft Indians, fourteenth Birch-bark Roll (1915)</nameofwork>
				<authorsname>Seton, Ernest Thompson (1860-1946)</authorsname>
				<language>English</language>
				<posteddate>Fri, 01 Feb 2013 07:14:43 -0500</posteddate>
				<genre>Spirituality</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4f96abd9ddb1a</library>
				</links>
				</project>
				<project id="projectID50f3082558bd8">
				<nameofwork>On Grandfather&#039;s Farm</nameofwork>
				<authorsname>Fréchette, Annie Thomas, 1844-1938 (neé Howells)</authorsname>
				<language>English</language>
				<posteddate>Fri, 01 Feb 2013 07:14:26 -0500</posteddate>
				<genre>Juvenile</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID50f3082558bd8</library>
				</links>
				</project>
				<project id="projectID4e4863607a745">
				<nameofwork>Our Young Folks 1867-10 Volume 3, Issue 10</nameofwork>
				<authorsname>J. T. Trowbridge, Gail Hamilton, and Lucy Larcom (Editors)</authorsname>
				<language>English</language>
				<posteddate>Fri, 01 Feb 2013 07:13:46 -0500</posteddate>
				<genre>Periodical</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4e4863607a745</library>
				</links>
				</project>
				<project id="projectID4fa4ae460e620">
				<nameofwork>The Montreal Medical Gazette, Volume 1, Issue 11 February 1845</nameofwork>
				<authorsname>William Sutherland (1815-1875),  Francis Badgley (1807-1863) (Editors)</authorsname>
				<language>English with French</language>
				<posteddate>Fri, 01 Feb 2013 07:10:55 -0500</posteddate>
				<genre>Medicine</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4fa4ae460e620</library>
				</links>
				</project>
				<project id="projectID4b01f3647137e">
				<nameofwork>How to Parse:</nameofwork>
				<authorsname>Edwin A. Abbott, D.D. (1838-1926)</authorsname>
				<language>English</language>
				<posteddate>Fri, 01 Feb 2013 04:29:59 -0500</posteddate>
				<genre>Literature</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4b01f3647137e</library>
				</links>
				</project>
				<project id="projectID4f7f35d46b81b">
				<nameofwork>The Treatment of Drapery in Art (1904)</nameofwork>
				<authorsname>Woolliscroft-Rhead, George (1855-1920)</authorsname>
				<language>English</language>
				<posteddate>Fri, 01 Feb 2013 03:33:54 -0500</posteddate>
				<genre>Art</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4f7f35d46b81b</library>
				</links>
				</project>
				<project id="projectID4ebd2ad515248">
				<nameofwork>A Widow&#039;s Tale and other stories</nameofwork>
				<authorsname>Oliphant, Margaret , (1828-1897)</authorsname>
				<language>English</language>
				<posteddate>Fri, 01 Feb 2013 03:33:01 -0500</posteddate>
				<genre>Short Story</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4ebd2ad515248</library>
				</links>
				</project>
				<project id="projectID4e3aa79b7c4b9">
				<nameofwork>Correspondence of Madame, Princess Palatine, etc. (1899)</nameofwork>
				<authorsname>Wormeley, Katharine Prescott (tr.)</authorsname>
				<language>English</language>
				<posteddate>Fri, 01 Feb 2013 03:32:10 -0500</posteddate>
				<genre>Correspondence</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4e3aa79b7c4b9</library>
				</links>
				</project>
				<project id="projectID4ef86bfc9215e">
				<nameofwork>Nelson&#039;s History of the War vol. 2 (1914)</nameofwork>
				<authorsname>Buchan, John (1875-1940)</authorsname>
				<language>English</language>
				<posteddate>Fri, 01 Feb 2013 03:31:21 -0500</posteddate>
				<genre>History</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4ef86bfc9215e</library>
				</links>
				</project>
				
				</projects>

=== de2164/dpcanada/trunk/d/xmlfeeds/posted.xml
<?xml version="1.0" encoding="utf-8" ?>
				<!-- Last Updated: Fri, 01 Feb 2013 19:49:00 -0500 -->
				<projects xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:noNamespaceSchemaLocation="projects.xsd">
				<project id="projectID4d0176bb1f64c">
				<nameofwork>The Inevitable Millionaires (1919)</nameofwork>
				<authorsname>E. Phillips Oppenheim (1866-1946)</authorsname>
				<language>English</language>
				<posteddate>Thu, 31 Jan 2013 16:59:37 -0500</posteddate>
				<genre>Mystery</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/20130142</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4d0176bb1f64c</library>
				</links>
				</project>
				<project id="projectID4b8fac85417ee">
				<nameofwork>Old Sultan; Grimm&#039;s Fairy Tales</nameofwork>
				<authorsname>Brothers Grimm</authorsname>
				<language>English</language>
				<posteddate>Thu, 31 Jan 2013 15:49:44 -0500</posteddate>
				<genre>Juvenile</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/20130141</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4b8fac85417ee</library>
				</links>
				</project>
				<project id="projectID504e554fc40f6">
				<nameofwork>The Cradle Ship (1916, 1941)</nameofwork>
				<authorsname>Howes, Edith (1872-1954); Florence Mary Anderson (1874 – 1930) illustrator</authorsname>
				<language>English</language>
				<posteddate>Thu, 31 Jan 2013 12:46:15 -0500</posteddate>
				<genre>Folklore</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/20130140</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID504e554fc40f6</library>
				</links>
				</project>
				<project id="projectID4bfeda5937efd">
				<nameofwork>The House of the Four Winds</nameofwork>
				<authorsname>Buchan, John ( 1875-1940)</authorsname>
				<language>English</language>
				<posteddate>Wed, 30 Jan 2013 21:24:55 -0500</posteddate>
				<genre>Adventure</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/20130139</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4bfeda5937efd</library>
				</links>
				</project>
				<project id="projectID4b7b07fbe63da">
				<nameofwork>Mrs Fox; Grimm&#039;s Fairy Tales</nameofwork>
				<authorsname>Brothers Grimm</authorsname>
				<language>English</language>
				<posteddate>Wed, 30 Jan 2013 17:35:37 -0500</posteddate>
				<genre>Juvenile</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/20130138</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4b7b07fbe63da</library>
				</links>
				</project>
				<project id="projectID4b7af02392c27">
				<nameofwork>Jorinda and Jorindel; Grimm&#039;s Fairy Tales</nameofwork>
				<authorsname>Brothers Grimm</authorsname>
				<language>English</language>
				<posteddate>Wed, 30 Jan 2013 15:48:59 -0500</posteddate>
				<genre>Juvenile</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/20130137</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4b7af02392c27</library>
				</links>
				</project>
				<project id="projectID486edc27c7725">
				<nameofwork>The Canadian Album Volume 1</nameofwork>
				<authorsname>Rev. William Cochrane (Editor)</authorsname>
				<language>English</language>
				<posteddate>Tue, 29 Jan 2013 01:10:10 -0500</posteddate>
				<genre>Biography</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/20130136</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID486edc27c7725</library>
				</links>
				</project>
				<project id="projectID4b1e5e70283ca">
				<nameofwork>La lucha por la vida: Aurora Roja</nameofwork>
				<authorsname>Pío Baroja</authorsname>
				<language>Spanish</language>
				<posteddate>Mon, 28 Jan 2013 17:09:55 -0500</posteddate>
				<genre>General Fiction</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/20130134</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4b1e5e70283ca</library>
				</links>
				</project>
				<project id="projectID4fb255c2b910b">
				<nameofwork>The Christian Recorder Vol. 1, Issue 7 (1819-September)</nameofwork>
				<authorsname>Various</authorsname>
				<language>English</language>
				<posteddate>Mon, 28 Jan 2013 16:42:14 -0500</posteddate>
				<genre>Religious</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/20130135</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4fb255c2b910b</library>
				</links>
				</project>
				<project id="projectID4fb2ff23b6176">
				<nameofwork>The Christian Recorder Vol. 1, Issue 10 (1819-December)</nameofwork>
				<authorsname>Various</authorsname>
				<language>English</language>
				<posteddate>Sun, 27 Jan 2013 17:33:54 -0500</posteddate>
				<genre>Religious</genre>
				<links>
				<PG_catalog>http://www.fadedpage.com/books/20130132</PG_catalog>
				<library>http://www.pgdpcanada.net/c/list_etexts.php?x=g&amp;sort=5#projectID4fb2ff23b6176</library>
				</links>
				</project>
				
				</projects>
